--
-- Файл сгенерирован с помощью SQLiteStudio v3.4.4 в Пт ноя 15 17:24:16 2024
--
-- Использованная кодировка текста: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: calalogs
CREATE TABLE IF NOT EXISTS calalogs (ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, NAME_CATALOG TEXT NOT NULL, CREATE_DATE_CATALOG TEXT NOT NULL);
INSERT INTO calalogs (ID, NAME_CATALOG, CREATE_DATE_CATALOG) VALUES (1, 'Основная категория', '15.11.2024');

-- Таблица: files
CREATE TABLE IF NOT EXISTS files (FILE_ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, ID_CATALOG INTEGER REFERENCES calalogs (ID) NOT NULL, FILE_NAME TEXT NOT NULL, SIZE INTEGER NOT NULL, CREATE_DATE_FILE TEXT NOT NULL, COUNT_LINES INTEGER NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
